name: Inference — Run emotion detection

on:
  workflow_dispatch:
    inputs:
      input_text:
        description: 'Type a sentence to classify'
        required: true
        default: 'I am feeling very happy today!'

jobs:
  infer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run inference
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          INPUT_TEXT: ${{ github.event.inputs.input_text }}
          HF_MODEL_NAME: g25ait2149/mlops-group28-emotion-distilbert-iitj
        run: python src/inference.py